exchangeManager = dofile("scripts\\Manager\\exchangeManager.lua")
statsManager = dofile("scripts\\Manager\\statsManager.lua")
hdvManager = dofile("scripts\\Manager\\hdvManager.lua")
famillierManager = dofile("scripts\\Manager\\famillierManager.lua")
stuffManager = dofile("scripts\\Manager\\stuffManager.lua")
