SYNC_MOVE = true

function stopped()
	printF.debug("goZap.lua", "stopped()")

	return stoppedManager.main()
end

function move()
	return {
		{ map = "191104002", path = "right"},	-- Banque Ext
		{ map = "192415750", path = "409" },		-- Banque Int

			-- Phenix Chafer
		{ map = "12,12", path = "havenbag"},

			-- Phenix Goultard
		{ map = "146800640", door = "333"},     -- int
		{ map = "147853315", path = "havenbag"}, -- Ext

		-- partie découverte

		{ map = "5,7", path = "left"},
		{ map = "4,7", path = "left"},
		{ map = "3,7", path = "left"},
		{ map = "2,7", path = "top"},
		{ map = "2,6", path = "top"},
		{ map = "2,5", path = "top"},
		{ map = "2,4", path = "left"},
		{ map = "1,4", path = "left"},
		{ map = "0,4", path = "left"},
		{ map = "-1,4", path = "top"},
		{ map = "-1,3", path = "top"},
		{ map = "-1,2", path = "top"},
		{ map = "-1,1", path = "left"},
		{ map = "-2,1", path = "top"},
		{ map = "-2,0", path = "top"},
		{ map = "-2,-1", path = "right"},
		{ map = "-1,-1", path = "right"},
		{ map = "0,-1", path = "right"},
		{ map = "1,-1", path = "right"},
		{ map = "2,-1", path = "top"},
		{ map = "88081177", path = "right"},
		{ map = "99095051", path = "410" },
		{ map = "3,-2", path = "top"},
		{ map = "3,-3", path = "right"},
		{ map = "4,-3", path = "top"},
		{ map = "4,-4", path = "top"},
		{ map = "4,-5", path = "left"},
		{ map = "3,-5", path = "top"},
		{ map = "3,-6", path = "right"},
		{ map = "4,-6", path = "right"},
		{ map = "5,-5", path = "right"},
		{ map = "5,-6", path = "right"},
		{ map = "6,-6", path = "right"},
		{ map = "6,-5", path = "top"},
		{ map = "7,-6", path = "right"},
		{ map = "8,-6", path = "bottom"},
		{ map = "8,-5", path = "bottom"},
		{ map = "8,-4", path = "left"},
		{ map = "7,-4", custom = end_of_zap }, -- Arrivée
		-- Arrivée











		{ map = "6,-17", path = "top"},
		{ map = "6,-18", path = "left"},
		{ map = "5,-18", path = "top"}, -- Déparat zap Astrub

		{ map = "5,-19", path = "left"},
		{ map = "4,-19", path = "left"},
		{ map = "3,-19", path = "bottom"},
		{ map = "3,-18", path = "left"},
		{ map = "2,-18", path = "left"},
		{ map = "1,-18", path = "left"},
		{ map = "0,-18", path = "left"},
		{ map = "-1,-18", path = "bottom"},
		{ map = "-1,-17", path = "bottom"},
		{ map = "-1,-16", path = "bottom"},
		{ map = "-1,-15", path = "bottom"},
		{ map = "-1,-14", path = "bottom"},
		{ map = "-1,-13", path = "bottom"},
		{ map = "-1,-12", path = "bottom"},
		{ map = "-1,-11", path = "bottom"},
		{ map = "-1,-10", path = "left"},
		{ map = "-2,-10", path = "left"},
		{ map = "-3,-10", path = "bottom"},
		{ map = "-3,-9", path = "bottom"},
		{ map = "-3,-8", path = "left"},
		{ map = "-4,-8", path = "left"},
		{ map = "-5,-8", path = "top"},
		{ map = "-6,-11", path = "right"},
		{ map = "-5,-11", path = "right"},
		{ map = "-4,-11", path = "right"},
		{ map = "-3,-11", path = "top"},
		{ map = "-3,-12", path = "top"},
		{ map = "-3,-13", path = "top"},
		{ map = "-3,-14", path = "top"},
		{ map = "-3,-15", path = "top"},
		{ map = "-3,-16", path = "top"},
		{ map = "-3,-17", path = "top"},
		{ map = "-3,-18", path = "top"},
		{ map = "-3,-19", path = "top"},
		{ map = "-3,-20", path = "top"},
		{ map = "-3,-21", path = "top"},
		{ map = "-3,-22", path = "top"},
		{ map = "-3,-23", path = "left"},
		{ map = "-4,-23", path = "left"},
		{ map = "-5,-23", path = "top"},
		{ map = "-5,-24", path = "top"},
		{ map = "-5,-25", path = "right"},
		{ map = "-4,-25", path = "right"},
		{ map = "-3,-25", path = "right"},
		{ map = "-2,-25", path = "right"},
		{ map = "-1,-25", path = "right"},
		{ map = "0,-25", path = "right"},
		{ map = "1,-25", path = "right"},
		{ map = "2,-25", path = "right"},
		{ map = "3,-25", path = "right"},
		{ map = "4,-25", path = "top"},
		{ map = "4,-26", path = "right"},
		{ map = "5,-26", path = "top"},
		{ map = "5,-27", path = "top"},
		{ map = "5,-28", path = "top"},
		{ map = "5,-29", path = "top"},
		{ map = "5,-30", path = "top"},
		{ map = "5,-31", path = "left"},
		{ map = "4,-31", path = "left"},
		{ map = "3,-31", path = "top"},
		{ map = "3,-32", path = "left"},
		{ map = "2,-32", path = "left"},
		{ map = "1,-32", path = "left"},
		{ map = "0,-32", path = "bottom"},
		{ map = "0,-31", path = "bottom"},
		{ map = "0,-30", path = "left"},
		{ map = "-1,-30", path = "left"},
		{ map = "-2,-30", path = "bottom"},
		{ map = "-2,-29", path = "bottom"},
		{ map = "-2,-28", path = "left"},
		{ map = "-3,-28", path = "left"},
		{ map = "-4,-28", path = "left"},
		{ map = "-5,-28", path = "left"},
		{ map = "-6,-28", path = "left"},
		{ map = "-7,-28", path = "bottom"},
		{ map = "-7,-27", path = "bottom"},
		{ map = "-7,-26", path = "bottom"},
		{ map = "-7,-25", path = "bottom"},
		{ map = "-7,-24", path = "bottom"},
		{ map = "-7,-23", path = "bottom"},
		{ map = "-7,-22", path = "bottom"},
		{ map = "-7,-21", path = "bottom"},
		{ map = "-7,-20", path = "left"},
		{ map = "-8,-20", path = "left"},
		{ map = "-9,-20", path = "left"},
		{ map = "-10,-20", path = "left"},
		{ map = "-11,-20", path = "top"},
		{ map = "-11,-21", path = "top"},
		{ map = "-11,-22", path = "left"},
		{ map = "-12,-22", path = "left"},
		{ map = "-13,-22", path = "top"},
		{ map = "-13,-23", path = "top"},
		{ map = "-13,-24", path = "top"},
		{ map = "-13,-25", path = "top"},
		{ map = "-13,-26", path = "top"},
		{ map = "-13,-27", path = "top"},
		{ map = "-13,-28", path = "top"},
		{ map = "-13,-29", path = "top"},
		{ map = "-13,-30", path = "top"},
		{ map = "-13,-31", path = "right"},
		{ map = "-12,-31", path = "top"},
		{ map = "-12,-32", path = "top"},
		{ map = "-12,-33", path = "top"},
		{ map = "-12,-34", path = "top"},
		{ map = "-12,-35", path = "right"},
		{ map = "-11,-35", path = "right"},
		{ map = "-10,-35", path = "right"},
		{ map = "-9,-35", path = "right"},
		{ map = "-8,-35", path = "right"},
		{ map = "-7,-35", path = "right"},
		{ map = "-6,-35", path = "right"},
		{ map = "-5,-35", path = "right"},
		{ map = "-4,-35", path = "right"},
		{ map = "-3,-35", path = "top"},
		{ map = "-3,-36", path = "top"},
		{ map = "-3,-37", path = "top"},
		{ map = "-3,-38", path = "top"},
		{ map = "-3,-39", path = "top"},
		{ map = "-3,-40", path = "top"},
		{ map = "-3,-41", path = "top"},
		{ map = "-3,-42", path = "top"},
		{ map = "-3,-43", path = "top"},
		{ map = "-3,-44", path = "top"},
		{ map = "-3,-45", path = "top"},
		{ map = "-3,-46", path = "top"},
		{ map = "-3,-47", path = "left"},
		{ map = "-4,-47", path = "left"},
		{ map = "-5,-47", path = "left"},
		{ map = "-6,-47", path = "left"},
		{ map = "-7,-47", path = "left"},
		{ map = "-8,-47", path = "left"},
		{ map = "-9,-47", path = "left"},
		{ map = "-10,-47", path = "left"},
		{ map = "-11,-47", path = "left"},
		{ map = "-12,-47", path = "left"},
		{ map = "-13,-47", path = "left"},
		{ map = "-14,-47", path = "left"},
		{ map = "-15,-47", path = "left"},
		{ map = "-16,-47", path = "left"},
		{ map = "-17,-47", path = "top"},
		{ map = "-17,-48", path = "top"},
		{ map = "-17,-49", path = "top"},
		{ map = "-17,-50", path = "top"},
		{ map = "-17,-51", path = "top"},
		{ map = "-17,-52", path = "top"},
		{ map = "-17,-53", path = "top"},
		{ map = "-17,-54", path = "top"},
		{ map = "-17,-55", path = "left"},
		{ map = "-18,-55", path = "left"},
		{ map = "-19,-55", path = "left"},
		{ map = "-20,-55", path = "left"},
		{ map = "-21,-55", path = "left"},
		{ map = "-22,-55", path = "left"},
		{ map = "-23,-55", path = "left"},
		{ map = "-24,-55", path = "top"},
		{ map = "-24,-56", path = "top"},

			-- Départ Bonta
		{ map = "-24,-57", door = "365"}, -- Bateau
		{ map = "-28,-56", path = "bottom"},
		{ map = "-28,-55", path = "left"},
		{ map = "-29,-55", path = "left"},
		{ map = "-30,-55", path = "top"},
		{ map = "-30,-56", door = "437"},
		{ map = "-31,-56", path = "bottom"},
		{ map = "-31,-55", path = "bottom"},
		{ map = "-31,-54", path = "bottom"},
		{ map = "-31,-53", path = "right"},
		{ map = "-30,-53", path = "right"},
		{ map = "-29,-53", path = "bottom"},
		{ map = "-28,-52", path = "bottom"},
		{ map = "-27,-51", path = "right"},
		{ map = "-26,-50", path = "right"},
		{ map = "-25,-49", path = "bottom"}, -- Sortie

		{ map = "-25,-48", path = "left"},
		{ map = "-26,-48", path = "left"},
		{ map = "-27,-48", path = "left"},
		{ map = "-28,-48", path = "bottom"},
		{ map = "-28,-47", path = "bottom"},
		{ map = "-28,-46", path = "bottom"},
		{ map = "-28,-45", path = "bottom"},
		{ map = "-28,-44", path = "bottom"},
		{ map = "-28,-43", path = "right"},
		{ map = "-27,-43", path = "bottom"},
		{ map = "-27,-42", path = "bottom"},
		{ map = "-27,-41", path = "bottom"},
		{ map = "-27,-40", path = "bottom"},
		{ map = "-27,-39", path = "bottom"},
		{ map = "-27,-38", path = "bottom"},
		{ map = "-27,-37", path = "bottom"},
		{ map = "-27,-36", path = "bottom"},
		{ map = "-27,-35", path = "right"},
		{ map = "-26,-35", path = "right"},
		{ map = "-25,-35", path = "right"},
		{ map = "-24,-35", path = "top"},
		{ map = "-24,-36", path = "right"},
		{ map = "-23,-35", path = "top"},
		{ map = "-23,-36", path = "right"},
		{ map = "-22,-36", path = "right"},
		{ map = "-21,-36", path = "right"},
		{ map = "-20,-36", path = "right"},
		{ map = "-19,-36", path = "bottom"},
		{ map = "-19,-35", path = "bottom"},
		{ map = "-19,-34", path = "bottom"},
		{ map = "-19,-33", path = "bottom"},
		{ map = "-19,-32", path = "bottom"},
		{ map = "-19,-31", path = "bottom"},
		{ map = "-19,-30", path = "left"},
		{ map = "-20,-30", path = "bottom"},
		{ map = "-20,-29", path = "bottom"},
		{ map = "-20,-28", path = "bottom"},
		{ map = "-20,-27", path = "bottom"},
		{ map = "-20,-26", path = "bottom"},
		{ map = "-20,-25", path = "bottom"},
		{ map = "-20,-24", path = "bottom"},
		{ map = "-20,-22", path = "bottom"},
		{ map = "-20,-23", path = "bottom"},
		{ map = "-20,-21", path = "bottom"},
		{ map = "-20,-20", path = "bottom"},
		{ map = "-20,-19", path = "bottom"},
		{ map = "-20,-18", path = "bottom"},
		{ map = "-20,-17", path = "bottom"},
		{ map = "-20,-16", path = "bottom"},
		{ map = "-20,-15", path = "left"},
		{ map = "-21,-15", path = "left"},
		{ map = "-22,-15", path = "bottom"},
		{ map = "-22,-14", path = "bottom"},
		{ map = "-22,-12", path = "bottom"},
		{ map = "-22,-13", path = "bottom"},
		{ map = "-22,-11", path = "bottom"},
		{ map = "-22,-10", path = "bottom"},
		{ map = "-22,-9", path = "bottom"},
		{ map = "-22,-8", path = "bottom"},
		{ map = "-22,-7", path = "bottom"},
		{ map = "-22,-6", path = "bottom"},
		{ map = "-22,-5", path = "left"},
		{ map = "-23,-5", path = "left"},
		{ map = "-24,-5", path = "bottom"},
		{ map = "-24,-4", path = "bottom"},
		{ map = "-24,-3", path = "bottom"},
		{ map = "-24,-2", path = "bottom"},
		{ map = "-24,0", path = "bottom"},
		{ map = "-24,-1", path = "bottom"},
		{ map = "-24,1", path = "bottom"},
		{ map = "-24,2", path = "bottom"},
		{ map = "-24,3", path = "left"},
		{ map = "-25,3", path = "bottom"},
		{ map = "-25,4", path = "right"},
		{ map = "-24,4", path = "bottom"},
		{ map = "-24,5", path = "bottom"},
		{ map = "-24,7", path = "bottom"},
		{ map = "-24,6", path = "bottom"},
		{ map = "-24,8", path = "left"},
		{ map = "-25,8", path = "bottom"},
		{ map = "-25,9", path = "bottom"},
		{ map = "-25,10", path = "bottom"},
		{ map = "-25,11", path = "bottom"},
		{ map = "-25,12", path = "bottom"},
		{ map = "-25,13", path = "right"},
		{ map = "-24,13", path = "bottom"},
		{ map = "-24,14", path = "right"},
		{ map = "-23,14", path = "bottom"},
		{ map = "-23,15", path = "bottom"},
		{ map = "-23,16", path = "right"},
		{ map = "-22,16", path = "bottom"},
		{ map = "-22,17", path = "bottom"},
		{ map = "-22,18", path = "bottom"},
		{ map = "-22,19", path = "bottom"},
		{ map = "-22,20", path = "right"},
		{ map = "-21,20", path = "bottom"},
		{ map = "-21,21", path = "right"},
		{ map = "-20,21", path = "bottom"},
		{ map = "-20,22", path = "bottom"},
		{ map = "-20,23", path = "bottom"},
		{ map = "-20,24", path = "left"},
		{ map = "-21,24", path = "bottom"},
		{ map = "-21,25", path = "bottom"},
		{ map = "-21,26", path = "bottom"},
		{ map = "-21,27", path = "bottom"},
		{ map = "-21,28", path = "bottom"},
		{ map = "-21,29", path = "left"},
		{ map = "-22,29", path = "left"},
		{ map = "-23,29", path = "left"},
		{ map = "-24,29", path = "bottom"},
		{ map = "-24,30", path = "left"},

		-- Brakmar
		{ map = "-25,30", path = "bottom"}, -- Entrée Brackmar
		{ map = "-26,31", path = "bottom"},
		{ map = "-26,32", path = "bottom"},
		{ map = "-26,33", path = "bottom"},
		{ map = "-26,35", path = "bottom"},
		{ map = "-26,34", path = "bottom"},
		{ map = "-26,36", path = "bottom"},
		{ map = "-26,37", path = "right"},
		{ map = "-25,37", door = "163"},
		{ map = "-23,36", path = "right"},
		{ map = "-22,36", path = "right"},
		{ map = "-21,36", path = "right"}, -- Sortie

		{ map = "-19,37", path = "top"},
		{ map = "-19,36", path = "right"},
		{ map = "-18,36", path = "top"},
		{ map = "-18,35", path = "top"},
		{ map = "-18,34", path = "right"},
		{ map = "-17,34", path = "top"},
		{ map = "-17,33", path = "top"},
		{ map = "-17,32", path = "top"},
		{ map = "-17,31", path = "right"},
		{ map = "-16,31", path = "top"},
		{ map = "-16,30", path = "right"},
		{ map = "-15,30", path = "top"},
		{ map = "-15,29", path = "top"},
		{ map = "-15,28", path = "right"},
		{ map = "-14,28", path = "right"},
		{ map = "-13,28", path = "right"},
		{ map = "-12,28", path = "right"},
		{ map = "-11,28", path = "right"},
		{ map = "-10,28", path = "right"},
		{ map = "-9,28", path = "top"},
		{ map = "-9,27", path = "top"},
		{ map = "-9,26", path = "right"},
		{ map = "-8,26", door = "530"},
		{ map = "-7,26", path = "right"},
		{ map = "-6,26", path = "right"},
		{ map = "-5,26", path = "right"},
		{ map = "-4,26", path = "right"},
		{ map = "-3,26", path = "right"},
		{ map = "-2,26", path = "top"},
		{ map = "-2,25", path = "top"},
		{ map = "-2,24", path = "right"},
		{ map = "-1,24", path = "right"},
		{ map = "0,24", path = "right"},
		{ map = "1,24", path = "right"},
		{ map = "2,24", path = "bottom"},
		{ map = "2,25", path = "bottom"},
		{ map = "2,26", path = "bottom"},
		{ map = "2,27", path = "right"},
		{ map = "3,27", path = "right"},
		{ map = "4,27", path = "bottom"},
		{ map = "4,28", path = "bottom"},
		{ map = "4,29", path = "right"},
		{ map = "5,29", path = "right"},
		{ map = "6,29", path = "right"},
		{ map = "7,29", path = "right"},
		{ map = "8,29", path = "right"},
		{ map = "9,29", path = "right"},
		{ map = "10,29", path = "right"},
		{ map = "11,29", path = "right"},

		-- Sufokia
		{ map = "12,29", path = "right"}, -- Entrée
		{ map = "13,29", path = "right"},
		{ map = "14,29", path = "top"},
		{ map = "14,28", path = "left"},
		{ map = "13,28", path = "top"},
		{ map = "13,27", path = "left"},
		{ map = "12,27", path = "top"},
		{ map = "12,26", path = "right"},
		{ map = "13,26", path = "right"},
		{ map = "14,26", path = "top"},
		{ map = "14,25", path = "right"},
		{ map = "15,25", path = "top"},
		{ map = "15,24", path = "top"},
		{ map = "15,23", path = "right"},
		{ map = "16,23", path = "top"},
		{ map = "16,22", path = "left"},
		{ map = "15,22", path = "left"}, -- Sortie


		{ map = "14,22", path = "top"},
		{ map = "14,21", path = "left"},
		{ map = "13,21", path = "left"},
		{ map = "12,21", path = "left"},
		{ map = "11,21", path = "left"},
		{ map = "10,21", path = "bottom"},
		{ map = "10,22", path = "left"},
		{ map = "9,22", path = "top"},
		{ map = "9,21", path = "top"},
		{ map = "9,20", path = "top"},
		{ map = "9,19", path = "left"},
		{ map = "8,19", path = "left"},
		{ map = "7,19", path = "left"},
		{ map = "6,19", path = "top"},
		{ map = "6,18", path = "top"},
		{ map = "6,17", path = "top"},
		{ map = "6,16", path = "top"},
		{ map = "6,15", path = "top"},
		{ map = "6,14", path = "top"},
		{ map = "6,13", path = "left"},
		{ map = "5,13", path = "left"},
		{ map = "4,13", path = "left"},
		{ map = "3,13", path = "left"},
		{ map = "2,13", path = "left"},
		{ map = "1,13", path = "left"},
		{ map = "0,13", path = "left"},
		{ map = "-1,13", path = "top"},
		{ map = "-1,12", path = "right"},
		{ map = "0,12", path = "right"},
		{ map = "1,12", path = "right"},
		{ map = "2,12", path = "right"},
		{ map = "3,12", path = "right"},
		{ map = "4,12", path = "right"},
		{ map = "5,12", path = "top"},
		{ map = "5,11", path = "top"},
		{ map = "5,10", path = "top"},
		{ map = "5,9", path = "top"},
		{ map = "5,8", path = "top"},
		{ map = "-5,-9", path = "left"},
		{ map = "-6,-9", path = "top"},
		{ map = "-6,-10", path = "top"},
	}
end
